name: deploy-core

on:
  push:
    branches:
      - develop
    paths:
      - Framework/core/**

defaults:
  run:
    working-directory: Framework/core

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm install
      - run: npm run build

      - name: "Azure login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: dist
          container_name: $web
          connection_string: ${{ secrets.AZURE_CONNECTION_STRING }}
          overwrite: 'true'
          sync: 'true'

      # az copy not working
      # - name: "Blob upload"
      #   uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #      az storage blob sync "dist" {{ secret.AZURE_BLOB_SAS_URL }}

      # Az storage blob sync not workint
      # - name: "Blob upload"
      #   uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #       az storage blob sync --account-name {{ secrets.AZURE_STORAGE_ACCOUNT }} --auth-mode key -c "$web" -s ./dist



