name: deploy-core

on:
  push:
    branches:
      - develop
    paths:
      - Framework/core/**

defaults:
  run:
    working-directory: Framework/core

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm install
      - run: npm run build

      - name: "Azure login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Blob upload"
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob sync --account-name {{ secrets.AZURE_STORAGE_ACCOUNT }} --auth-mode key -c "$web" -s ./dist

